<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>scopeName</key>
    <string>text.gdl</string>
        
	<key>fileTypes</key>
	<array>
		<string>gdl</string>
	</array>
    
	<key>foldingStartMarker</key>
	<string>(?i)(?&lt;=^|\s)((!\s&lt;.*$)|^[0-9]+:|ADD[2XYZ]?|MUL[2XYZ]?|ROT[2XYZ]?|XFORM|CUTPOLY[A]?|CUTSHAPE|CUTFORM|GROUP|FOR|WHILE|REPEAT)(?=$|\s)</string>
    
	<key>foldingStopMarker</key>
	<string>(?i)(?&lt;=^|\s)((!\s&gt;.*$)|^RETURN|DEL(\sTOP)?|ENDGROUP|NEXT|ENDWHILE|UNTIL)(?=$|\s)</string>
    
	<key>name</key>
	<string>GDL file</string>
    
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>!</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.block.gdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\b[0-9]*:)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.label</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\"[^\"]*\"</string>
			<key>name</key>
			<string>string.gdl</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(ADD[2XYZ]?|MUL[2XYZ]?|ROT[2XYZ]?|XFORM|DEL(\sTOP)?)(?=$|\s|\^|\*\*|\/|\+|\-|\=|\&lt;|\&gt;|\&lt;\=|\&gt;\=|\&lt;\&gt;|\#)</string>
			<key>name</key>
			<string>keyword.gdl.transform</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(LINE2|RECT2|POLY2_A|POLY2_B(\{[2-4]\})?|POLY2_|POLY2|ARC2|CIRCLE2|SPLINE2[A]?|PICTURE2(\{2\})?|TEXT2|RICHTEXT2)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.shape.2D</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(BLOCK|BRICK|CYLIND|SPHERE|ELLIPS|CONE|PRISM[_]?|CPRISM_(\{2\})?|BPRISM_|FPRISM_|HPRISM_|SPRISM_(\{2\})?|SLAB[_]?|CSLAB_|CWALL_|BWALL_|XWALL_(\{2\})?|BEAM|CROOF_(\{2\})?|MESH|ARM[CE]|ELBOW)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.shape.3D.basic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(LIN_|RECT|POLY[_]?|PLANE[_]?|CIRCLE|ARC)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.shape.3D.planar</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(EXTRUDE|PYRAMID|REVOLVE|RULED(\{2\})?|SWEEP|TUBE[A]?|COONS|MASS)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.shape.3D.poly</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(LIGHT|PICTURE)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.shape.3D.viz</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(TEXT|RICHTEXT)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.shape.3D.text</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(VERT|TEVE|VECT|EDGE|PGON|PIPG|COOR|BODY|BASE)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.shape.3D.primitive</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(CUTPLANE(\{[2-3]\})?|CUTPOLY[A]?|CUTSHAPE|CUTFORM|CUTEND)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.shape.3D.cut</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(GROUP|ENDGROUP|ADDGROUP|SUBGROUP|ISECTGROUP|ISECTLINES|PLACEGROUP|KILLGROUP|SWEEPGROUP)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.shape.3D.seo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(BINARY)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.shape.3D.binary</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(FRAGMENT[2]?|PROJECT2(\{[2-3]\})?|DRAWING(2|3(\{[2-3]\})?))(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.symbol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(HOTSPOT[2]?|HOTLINE[2]?|HOTARC[2]?)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.editing</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(LET|RADIUS|RESOL|TOLER|PEN|LINE_PROPERTY|(SET\s)?STYLE|(SET\s)?MATERIAL|MODEL|SECT_FILL|SECT_ATTRS|SHADOW|DRAWINDEX|(SET\s)?FILL|(SET\s)?LINE_TYPE)(?=$|\s|\^|\*\*|\/|\+|\-|\=|\&lt;|\&gt;|\&lt;\=|\&gt;\=|\&lt;\&gt;|\#)</string>
			<key>name</key>
			<string>keyword.gdl.attribute.directive</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(DEFINE\s(MATERIAL|TEXTURE|FILL[A]?|SYMBOL_FILL|SOLID_FILL|EMPTY_FILL|LINEAR_GRADIENT_FILL|RADIAL_GRADIENT_FILL|TRANSLUCENT_FILL|IMAGE_FILL|LINE_TYPE|SYMBOL_LINE|STYLE(\{2\})?)|PARAGRAPH|ENDPARAGRAPH|TEXTBLOCK|ADDITIONAL_DATA|FILE_DEPENDENCE)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.attribute.definition</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(DATABASE_SET|DESCRIPTOR|REF DESCRIPTOR|COMPONENT|REF COMPONENT|BINARYPROP|SURFACE3D|VOLUME3D|POSITION|DRAWING)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.nongeo.properties</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(VALUES|PARAMETERS|LOCK|HIDEPARAMETER)(\{2\})?(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.nongeo.parameters</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(UI_(DIALOG|PAGE|CURRENT_PAGE|BUTTON|SEPARATOR|GROUPBOX|PICT|STYLE|OUTFIELD|INFIELD|PICT_BUTTON(\{[2-3]\})?|RADIOBUTTON|TOOLTIP))(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.nongeo.ui</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(DIM|VARDIM[1-2]?)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.functions.expression</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(\^|\*\*|\/|\+|\-|\=|\&lt;|\&gt;|\&lt;\=|\&gt;\=|\&lt;\&gt;|\#)|(?&lt;=^|\s)(MOD|AND|OR|EXOR|\&amp;|\||\@)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.functions.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(ABS|CEIL|INT|FRA|ROUND_INT|SGN|SQR|ACS|ASN|ATN|COS|SIN|TAN|PI|EXP|LGT|LOG|NOT|MIN|MAX|RND|BITTEST|BITSET|REQ(UEST)?|IND|STR(\{2\})?|SPLIT|STW|STRLEN|STRSTR|STRSUB)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.functions.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(FOR|TO|STEP|NEXT|DO|WHILE|ENDWHILE|REPEAT|UNTIL|IF|THEN|ELSE|ENDIF|GOTO|GOSUB|RETURN|END|EXIT|BREAKPOINT)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.control.flow</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(CALL)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.control.macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(OPEN|INPUT|VARTYPE|OUTPUT|CLOSE)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.control.fileops</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s|\^|\*\*|\/|\+|\-|\=|\&lt;|\&gt;|\&lt;\=|\&gt;\=|\&lt;\&gt;|\#)(GLOB_SCRIPT_TYPE|T~|GLOB_CONTEXT|GLOB_SCALE|A_|GLOB_DRAWING_BGD_PEN|GLOB_NORTH_DIR|U~|GLOB_WORLD_ORIGO_OFFSET_X|GLOB_WORLD_ORIGO_OFFSET_Y|GLOB_MODPAR_NAME|GLOB_UI_BUTTON_ID|GLOB_CUTPLANES_INFO|GLOB_STRUCTURE_DISPLAY)(?=$|\s|\^|\*\*|\/|\+|\-|\=|\&lt;|\&gt;|\&lt;\=|\&gt;\=|\&lt;\&gt;|\#)</string>
			<key>name</key>
			<string>keyword.gdl.globals.general</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s|\^|\*\*|\/|\+|\-|\=|\&lt;|\&gt;|\&lt;\=|\&gt;\=|\&lt;\&gt;|\#)(GLOB_HSTORY_ELEV|B_|GLOB_HSTORY_HEIGHT|Q_|GLOB_CSTORY_ELEV|Q~|GLOB_CSTORY_HEIGHT|R~|GLOB_CH_STORY_DIST|S~)(?=$|\s|\^|\*\*|\/|\+|\-|\=|\&lt;|\&gt;|\&lt;\=|\&gt;\=|\&lt;\&gt;|\#)</string>
			<key>name</key>
			<string>keyword.gdl.globals.story</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s|\^|\*\*|\/|\+|\-|\=|\&lt;|\&gt;|\&lt;\=|\&gt;\=|\&lt;\&gt;|\#)(GLOB_LAYER|GLOB_ID|GLOB_INTGUID|GLOB_ELEVATION|GLOB_ELEM_TYPE)(?=$|\s|\^|\*\*|\/|\+|\-|\=|\&lt;|\&gt;|\&lt;\=|\&gt;\=|\&lt;\&gt;|\#)</string>
			<key>name</key>
			<string>keyword.gdl.globals.elementpara</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s|\^|\*\*|\/|\+|\-|\=|\&lt;|\&gt;|\&lt;\=|\&gt;\=|\&lt;\&gt;|\#)(SYMB_LINETYPE|SYMB_FILL|SYMB_FILL_PEN|SYMB_FBGD_PEN|SYMB_SECT_PEN|SYMB_VIEW_PEN|L_|SYMB_MAT|M_|SYMB_POS_X|X~|SYMB_POS_Y|Y~|SYMB_POS_Z|Z~|SYMB_ROTANGLE|W~|SYMB_MIRRORED|V~|SYMB_A_SIZE|SYMB_B_SIZE|SYMB_Z_SIZE)(?=$|\s|\^|\*\*|\/|\+|\-|\=|\&lt;|\&gt;|\&lt;\=|\&gt;\=|\&lt;\&gt;|\#)</string>
			<key>name</key>
			<string>keyword.gdl.globals.objectpara</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s)(APPLICATION_QUERY)(?=$|\s)</string>
			<key>name</key>
			<string>keyword.gdl.request.appquery</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(?&lt;=^|\s|\^|\*\*|\/|\+|\-|\=|\&lt;|\&gt;|\&lt;\=|\&gt;\=|\&lt;\&gt;|\#)(LIBRARYGLOBAL)(?=$|\s|\^|\*\*|\/|\+|\-|\=|\&lt;|\&gt;|\&lt;\=|\&gt;\=|\&lt;\&gt;|\#)</string>
			<key>name</key>
			<string>keyword.gdl.request.libraryglobal</string>
		</dict>
	</array>

</dict>
</plist>
